"""Rebuild the baked wordmark: python + Pillow, NumPy, SciPy; no runtime font dependency."""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import distance_transform_edt
import numpy as np
import zlib, base64
root = Path(__file__).resolve().parents[1]
w,h=384,144
mask=Image.new('L',(w,h)); draw=ImageDraw.Draw(mask)
font=ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSansMono-BoldOblique.ttf',104)
draw.text((10,3),'PITER',font=font,fill=255,stroke_width=0)
bbox=mask.getbbox(); crop=mask.crop(bbox); crop.thumbnail((344,86))
mask=Image.new('L',(w,h)); mask.paste(crop,(12,20))
solid=np.array(mask)>100
inside=distance_transform_edt(solid)
gy,gx=np.gradient(np.minimum(inside,5))
y,x=np.indices((h,w)); field=np.zeros((h,w),dtype=float)
# Extruded rear surfaces, then polished front and bevel.
for depth in range(14,0,-1):
    shifted=np.zeros_like(solid); shifted[depth:,depth:]=solid[:-depth,:-depth]
    field[shifted]=52+30*(1-depth/14)+12*np.sin(y[shifted]*.4)
face=155+45*np.cos((y-20)/86*6.28)+14*np.sin(x*.015)
bevel=np.clip(185-65*gx-90*gy,70,255)
field[solid]=np.where(inside[solid]<5,bevel[solid],face[solid])
raw=np.clip(field,0,255).astype('uint8').tobytes()
data=base64.b64encode(zlib.compress(raw,9)).decode()
(root/'extensions/wordmark-data.ts').write_text('// Generated by scripts/build-wordmark.py. Baked lighting; no runtime fonts.\nimport { inflateSync } from \'node:zlib\';\nexport const artWidth = 384, artHeight = 144;\nexport const art = inflateSync(Buffer.from(\''+data+'\', \'base64\'));\n')
